package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u192/11895/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Saturday, October 6, 2018 6:46:22 AM PDT
*/

public interface LIFESPAN_POLICY_ID
{

  /**
  	 * The value representing LIFESPAN_POLICY_ID.
  	 */
  public static final int value = (int)(17L);
}
